version: '3.8'

services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: video-upload-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-supersecret_dev_root_password}
      MYSQL_DATABASE: ${DB_NAME:-video_service_db}
      MYSQL_USER: ${DB_USER:-video_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-video_password}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          '${DB_USER:-video_user}',
          '-p${DB_PASSWORD:-video_password}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
